### ISSUE TITLE
Add/Edit Member - SRSC_2.2.1

### ISSUE THREAD

**Issue by Tabassum-momin** [aakvatech/LibMS#32]
Library user should be able to view all members and perform below actions:

- [ ] 1. Add Member and membership details (More than one membership type allowed)
- [ ] 2. Print Registration form
- [ ] 3. Issue membership Card (Out of scope. Digital card is used instead)
- [ ] 4. View Current Membership details, card and memberhsip history
- [ ] 5. Edit Member details
- [ ] 6. View Membership Card
- [ ] 7. Terminate Membership - Change status to 'terminated' to block transactions.
- [ ] 8. Renew Membership ('Till Last Issue Date' field is Deprecated)
- [ ] 9. Search through member list based on Name and registration number.

**Comment by Tabassum-momin** [comment]
For task #1, 
1. An error ops-up when new member form is submitted.

> ### App Versions
```
{
	"erpnext": "15.14.2",
	"frappe": "15.14.0",
	"library_management": "0.0.1",
	"payments": "0.0.1"
}
```
### Route
```
Form/Member/MLJS00019
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 863, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/notifications.py", line 289, in get_open_count
    external_links_data_for_d = get_external_links(d, name, links)
  File "apps/frappe/frappe/desk/notifications.py", line 347, in get_external_links
    frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 1971, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1946, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 192, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 236, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 234, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabCustomer.customer' in 'where clause'")

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Member",
		"name": "MLJS00017",
		"items": "[\"Book Transaction\",\"Library Membership\",\"Customer\"]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.notifications.get_open_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabCustomer.customer' in 'where clause'\")",
	"exc_type": "OperationalError"
}
```

2. An error pops-up during while submitting a library membership form
![image](https://github.com/aakvatech/LibMS/assets/74194965/2137967f-c289-4262-8828-726bb7fc6431)

**Comment by ramjanalitech** [comment]
https://github.com/aakvatech/LibMS/issues/32#issuecomment-2185741206


the issue has been resolved

**Comment by ramjanalitech** [comment]
Point 7
![Screenshot 2024-06-24 at 12 53 31 PM](https://github.com/aakvatech/LibMS/assets/144917268/8b156bb4-1bd3-44e3-b0ed-38310529b1f0)


> Library user should be able to view all members and perform below actions:
> 
> * [ ]  1. Add Member and membership details (More than one membership type allowed)
> * [ ]  2. Print Registration form
> * [ ]  3. Issue membership Card (Out of scope. Digital card is used instead)
> * [ ]  4. View Current Membership details, card and memberhsip history
> * [ ]  5. Edit Member details
> * [ ]  6. View Membership Card
> * [ ]  7. Terminate Membership - Change status to 'terminated' to block transactions.
> * [ ]  8. Renew Membership ('Till Last Issue Date' field is Deprecated)
> * [x]  9. Search through member list based on Name and registration number.

**Comment by Tabassum-momin** [comment]
- #6  - Exception thrown when a print format "wewe" is selected
- #3 - Is there a way to send the card link through SMS?
- #7 - Need a mechanism to change status of 'disabled' User to 'Active'
- 
-

**Comment by Tabassum-momin** [comment]
![image](https://github.com/user-attachments/assets/c1b2b10d-4d1b-43a3-8cca-88b9d96e1dbd)
